name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Syncthing
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Deploy network
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: syncthing-network
        template: setups/aws/templates/network.yml
        no-fail-on-empty-changeset: 1

    #- name: Deploy ELB
    #  uses: aws-actions/aws-cloudformation-github-deploy@v1
    #  with:
    #    name: syncthing-elb
    #    template: setups/aws/templates/elb.yml
    #    no-fail-on-empty-changeset: 1

    #- name: Deploy EFS
    #  uses: aws-actions/aws-cloudformation-github-deploy@v1
    #  with:
    #    name: syncthing-efs
    #    template: setups/aws/templates/efs.yml
    #    no-fail-on-empty-changeset: 1
    
    #- name: Deploy Syncthing
    #  uses: aws-actions/aws-cloudformation-github-deploy@v1
    #  with:
    #    name: syncthing-ecs
    #    template: setups/aws/templates/syncthing.yml
    #    parameter-overrides: "Revision=${{ github.run_id }}"
    #    no-fail-on-empty-changeset: 1
